/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MorphoLendingContract } from "./MorphoLendingContract";
export * as factories from "./factories";
export { MorphoLendingContract__factory } from "./factories/MorphoLendingContract__factory";
