/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VenusLendingContract } from "./VenusLendingContract";
export * as factories from "./factories";
export { VenusLendingContract__factory } from "./factories/VenusLendingContract__factory";
